### ISSUE TITLE
Find a better way to scrape the port number

### ISSUE THREAD

**Issue by abliss** [Floobits/floobits-emacs#73]
I'm super excited to try floobits in emacs, but the plugin doesn't work for me. I've chased the issue down to the way the elisp is trying to scrape the port number from the python process. For some reason it never triggers. I first thought was that it might be the slowness of my system causing it to get missed (e.g. the python process spits out the number before emacs is ready to catch it), but I increased the set_timeout in floobits.py:36 to 10000, which gave emacs plenty of time to set up the *Floobits* buffer. Somehow the message never shows up in the buffer, and so the floobits connection never gets started.

If I run floobits.py from the commandline, it prints "now listening on XXXX" which seems to be the correct behavior.

If I run `ps` I can see that emacs did indeed launch a floobits.py subprocess, and if I use `lsof` I can find that it is listening on some random portnumber. I can then manually plug that port number into the elisp code from floobits-agent-listener; this then calls floobits-on-connect and everything seems to work great.

So, as I said, the problem seems to be the way that the elisp is trying to get the port number from the python process.

I still don't know why it doesn't work for me. But it seems like a pretty error-prone mechanism in general. (Why is the timeout in floobits.py set to 100ms? Is that how long your emacs24 takes to create a new *Floobits*  buffer? If so, that's a pretty fragile hack.) Surely there's a better way to get the port number? Maybe you could have the floobits.py create a file with the port number in ~/.floobits (like the way the emacs server does in TCP mode). Or you could use a named local socket instead of a random port number.  Or you could have the elisp run `ps` and `lsof` to try to look up the port number.  If any of those sounds good to you, let me know and I'll be happy to send you a pull request.

**Comment by ggreer** [comment]
Nice troubleshooting. Could you give versions of your OS, python, and emacs? We've tested this plugin on a bunch of combinations, and it should work on anything that isn't Windows.

The 100ms timeout in python-land is a hack. We just want to make sure we're listening on the port before sending the info to emacs. The right way to do this is to add a callback to the listen function, but that would require some other changes in code shared with our Sublime and Neovim plugins.

Using files introduces more complexity, because there are more ways in which it can fail. What if the disk is full? What if permissions forbid writing to the desired path? What if emacs crashes (or is killed) and leaves a stale file sitting around? Etc. Spawning a child process and reading its stdout is about as foolproof as you can get.

I'm very curious why your emacs isn't reading the stdout correctly. Is it possible that something in your `~/.emacs` is causing the issue?

**Comment by ggreer** [comment]
I just thought of something. We're not flushing stdout in python.

Oops.

**Comment by abliss** [comment]
Yep, adding a sys.stdout.flush() to floobits.py does seems to fix the
problem.

I am using an armv7l linux (android) device, in an ubuntu-10.04 chroot. I
built emacs 24.4.1 (with no X toolkit) myself since I couldn't find an
appropriate binary distribution. I'm using python 2.7.3 from ubuntu.

You raise some good points about the filesystem. And I suppose named local
sockets present a portability concern. And I presume you have some good
reason to use a socket in the first place instead of doing all your comms
through stdin/stdout. Have you considered letting the elisp choose the
random port, and pass it as a commandline flag to the subprocess?

**Comment by ggreer** [comment]
I'm glad it's such a simple fix. I've updated master with a `stdout.flush()` and some better error handling.

Python doesn't randomly generate a port number and then listen on it. It calls listen() with a port of 0, which is guaranteed by the OS to pick an available port. Any other flow (such as checking if the port is available, then trying to listen on it) is vulnerable to race conditions. Another process could take that port in the time between the check and the call to listen().

**Comment by ggreer** [comment]
Closing since this is fixed.
